import React, { useState, useEffect } from "react";
import {
  Search,
  Eye,
  Trash2,
  Sparkles,
  Calendar,
  Pencil, // Added Pencil Icon
} from "lucide-react";
import { format } from "date-fns";
import useAuth from "../hooks/useAuth";
import { ENDPOINTS } from "../config";
import ShowOriginalPost from "../components/ShowOriginalPost";
import EditRewrittenPost from "../components/EditRewrittenPost"; // Import Edit Modal

const RewrittenPosts = () => {
  const { user } = useAuth();
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(0);

  // Modal States
  const [selectedPost, setSelectedPost] = useState(null);
  const [isViewModalOpen, setIsViewModalOpen] = useState(false);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false); // Edit Modal State

  useEffect(() => {
    fetchPosts();
  }, [page, searchTerm]);

  const fetchPosts = async () => {
    setLoading(true);
    try {
      let url = `${ENDPOINTS.REWRITTEN_POSTS}?pageNumber=${page}`;
      if (searchTerm) url += `&keyword=${searchTerm}`;

      const response = await fetch(url, {
        headers: { Authorization: `Bearer ${user.token}` },
      });
      const data = await response.json();

      setPosts(data.posts || []);
      setTotalPages(data.pages || 0);
    } catch (error) {
      console.error("Error fetching posts:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id) => {
    if (
      !window.confirm(
        "Are you sure you want to delete this AI rewritten article?",
      )
    )
      return;
    try {
      await fetch(`${ENDPOINTS.REWRITTEN_POSTS}/${id}`, {
        method: "DELETE",
        headers: { Authorization: `Bearer ${user.token}` },
      });
      setPosts(posts.filter((post) => post._id !== id));
    } catch (error) {
      alert("Failed to delete post");
    }
  };

  // Called when Edit Modal saves successfully
  const handlePostUpdate = (updatedPost) => {
    setPosts(posts.map((p) => (p._id === updatedPost._id ? updatedPost : p)));
  };

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <Sparkles className="text-purple-500" /> Rewritten Posts (AI)
          </h1>
          <p className="text-slate-500 dark:text-slate-400">
            Unique content generated by Gemini AI.
          </p>
        </div>
      </div>

      {/* Search Bar */}
      <div className="relative">
        <Search
          className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"
          size={20}
        />
        <input
          type="text"
          placeholder="Search rewritten titles..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="w-full pl-10 pr-4 py-3 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none transition-all"
        />
      </div>

      {/* Table */}
      <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 dark:bg-slate-900/50 border-b border-slate-200 dark:border-slate-700 text-xs uppercase tracking-wider text-slate-500 font-medium">
                <th className="p-4 w-16">Image</th>
                <th className="p-4">Title</th>
                <th className="p-4 w-40">AI Model</th>
                <th className="p-4 w-40">Date</th>
                <th className="p-4 w-40 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
              {loading ? (
                <tr>
                  <td colSpan="5" className="p-8 text-center text-slate-500">
                    Loading posts...
                  </td>
                </tr>
              ) : posts.length === 0 ? (
                <tr>
                  <td colSpan="5" className="p-8 text-center text-slate-500">
                    No rewritten posts found. Go convert some!
                  </td>
                </tr>
              ) : (
                posts.map((post) => (
                  <tr
                    key={post._id}
                    className="hover:bg-slate-50 dark:hover:bg-slate-700/30 transition-colors"
                  >
                    <td className="p-4 align-top">
                      <div className="w-12 h-12 rounded-lg bg-slate-100 dark:bg-slate-800 overflow-hidden border border-slate-200 dark:border-slate-700">
                        {post.featuredImage && (
                          <img
                            src={post.featuredImage}
                            alt=""
                            className="w-full h-full object-cover"
                            onError={(e) => (e.target.style.display = "none")}
                          />
                        )}
                      </div>
                    </td>
                    <td className="p-4 align-top">
                      <h3 className="font-semibold text-slate-900 dark:text-white line-clamp-2">
                        {post.title}
                      </h3>
                    </td>
                    <td className="p-4 align-top">
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-purple-50 text-purple-700 border border-purple-200">
                        {post.aiModel || "Gemini"}
                      </span>
                    </td>
                    <td className="p-4 align-top text-sm text-slate-500">
                      <div className="flex items-center gap-1.5">
                        <Calendar size={14} />
                        {format(new Date(post.createdAt), "MMM d")}
                      </div>
                    </td>
                    <td className="p-4 align-top text-right">
                      <div className="flex justify-end gap-1">
                        {/* VIEW BUTTON */}
                        <button
                          onClick={() => {
                            setSelectedPost(post);
                            setIsViewModalOpen(true);
                          }}
                          className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition"
                          title="View"
                        >
                          <Eye size={18} />
                        </button>

                        {/* EDIT BUTTON (NEW) */}
                        <button
                          onClick={() => {
                            setSelectedPost(post);
                            setIsEditModalOpen(true);
                          }}
                          className="p-2 text-slate-400 hover:text-green-600 hover:bg-green-50 rounded-lg transition"
                          title="Edit"
                        >
                          <Pencil size={18} />
                        </button>

                        {/* DELETE BUTTON */}
                        <button
                          onClick={() => handleDelete(post._id)}
                          className="p-2 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition"
                          title="Delete"
                        >
                          <Trash2 size={18} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="flex justify-center p-4 border-t border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50">
            <div className="flex gap-2">
              <button
                disabled={page === 1}
                onClick={() => setPage(page - 1)}
                className="px-3 py-1 text-sm rounded bg-white dark:bg-slate-800 border hover:bg-slate-50"
              >
                Previous
              </button>
              <span className="px-3 py-1 text-sm text-slate-600 self-center">
                Page {page} of {totalPages}
              </span>
              <button
                disabled={page === totalPages}
                onClick={() => setPage(page + 1)}
                className="px-3 py-1 text-sm rounded bg-white dark:bg-slate-800 border hover:bg-slate-50"
              >
                Next
              </button>
            </div>
          </div>
        )}
      </div>

      {/* View Modal (Reuse existing) */}
      <ShowOriginalPost
        isOpen={isViewModalOpen}
        onClose={() => setIsViewModalOpen(false)}
        post={selectedPost}
      />

      {/* Edit Modal (New) */}
      <EditRewrittenPost
        isOpen={isEditModalOpen}
        onClose={() => setIsEditModalOpen(false)}
        post={selectedPost}
        onUpdate={handlePostUpdate}
      />
    </div>
  );
};

export default RewrittenPosts;
